

DEFAULT_OUTPUT_DIR = "results"
DEFAULT_TRANFORMATION_COMPARISON_DIR = DEFAULT_OUTPUT_DIR + "/transformations"

META_INFORMATION_FILENAME = "meta-information.json"
SOURCE_INFORMATION_FILENAME = "source-information.json"